language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"
# command to install dependencies
install:
  - pip install -r deploy/requirements.txt
# command to run tests
script:
  - python3 -m unittest
